#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define HALITE_VERSION					0,2,9,259
#define HALITE_VERSION_STRING			"v 0.2.9 dev 259"

#define HALITE_LANGUAGE					10
#define IDC_DEBUGLISTVIEW               1
#define IDR_LISTVIEW_MENU               101
#define IDD_CONFIGBIT                   102
#define IDD_CONFIGREMOTE                103
#define IDD_CONFIGSECURITY              108
#define IDD_CONFIGPROXY                 109
#define IDD_ABOUT                       104
#define IDD_CLOSESPLASH                 105
#define IDD_HALITEDLG                   106
#define IDR_TRAY_MENU                   107
#define IDD_NEWTORRENT                  111
#define IDD_CONFIGGENERAL               112
#define IDD_ADVHALITEDLG                114
#define IDR_APP_ICON                    114
#define IDD_THEMETEST                   115
#define IDD_DEBUGDIALOG                 116
#define IDD_PROGRESS                    117
#define IDD_CONFIGTORRENT               118
#define IDD_ADVOVERVIEW                 119
#define IDD_ADVTRACKER                  120
#define IDD_ADVDEBUGLOG                 121
#define IDR_MAINFRAME                   128
#define IDD_TRACKEDIT                   130
#define IDD_ADVPEER                     131
#define IDR_TRACKERLV_MENU              132
#define IDC_TRANS_SES                   1004
#define IDC_TRANS_ETA                   1005
#define IDC_PEERPROXY                   1000
#define IDC_WEBPROXY                    1001
#define IDC_TRACKERPROXY                1002
#define IDC_DHTPROXY                    1003
#define IDC_TRANS                       1000
#define LISTPEERS                       1000
#define IDC_PEERLIST                    1000
#define IDC_RATIOSTAT                   1001
#define IDC_TRACKER_EDIT_TIER           1001
#define IDC_RATIOESTATIC                1002
#define IDC_TRACKER_EDIT_URL            1002
#define IDC_TRACKER_RESET               1002
#define IDC_BC_DHTPORT_S                1003
#define IDC_TRACKER_APPLY               1003
#define TORRENTPROG                     1003
#define IDC_BC_DHTPORT                  1004
#define IDC_COMPLETE                    1004
#define ID_SETTINGS                     1004
#define IDC_BC_PROMPTSAVE               1005
#define ID_RESUME                       1005
#define ID_PAUSE                        1006
#define IDC_SPLASH_MSG                  1007
#define IDC_NAME                        1008
#define IDC_TRACKER                     1009
#define IDC_STATUS                      1010
#define IDC_AVAIL                       1011
#define BTNREMOVE                       1012
#define BTNREANNOUNCE                   1013
#define IDC_EDITTLU                     1014
#define IDC_EDITTLD                     1015
#define IDC_EDITNCD                     1016
#define IDC_EDITNCU                     1017
#define IDC_EDITRATIO                   1018
#define IDC_TLD                         1019
#define IDC_TLU                         1020
#define IDC_TL                          1021
#define IDC_NCU                         1022
#define IDC_NCD                         1023
#define IDC_DETAILS_GROUP               1024
#define IDC_BC_MAXCONN                  1025
#define IDC_UPDATE                      1025
#define IDC_BC_TMAXCONN                 1026
#define IDC_REMOTECTRL                  1026
#define IDC_BC_MAXUP                    1027
#define IDC_RATIO                       1027
#define IDC_BC_TMAXUP                   1028
#define IDC_ETA                         1028
#define IDC_REMOTEPORT                  1028
#define IDC_BC_PORTFROM                 1029
#define IDC_BC_SAVEFOLDER               1029
#define IDC_BC_PORTTO                   1030
#define IDC_BC_DOWNRATE                 1031
#define IDC_BC_TDOWNRATE                1032
#define IDC_BC_UPRATE                   1033
#define BTNPAUSE                        1034
#define IDC_BC_TUPRATE                  1034
#define IDC_NEWT_BROWSE                 1035
#define IDC_NEWT_FILE                   1036
#define IDC_NEWT_TRACKER                1037
#define IDC_NEWT_LISTTRACKERS           1038
#define IDC_NEWT_DHTNODE                1039
#define IDC_NEWT_ADDTRACKER             1040
#define IDC_BUTTON1                     1041
#define IDC_EDIT1                       1042
#define IDC_EDIT2                       1043
#define IDC_GENERAL_ONEINST             1043
#define IDC_GENERAL_ADVGUI              1044
#define IDC_TAB                         1044
#define IDC_CHECK1                      1045
#define IDC_GENERAL_TRAY                1045
#define IDC_RADIO1                      1046
#define IDC_BC_DHT                      1048
#define IDC_PROG_PROGRESS               1048
#define IDC_BC_FILTERCHECK              1049
#define IDC_PROG_CANCEL                 1049
#define IDC_BC_FILTERLOAD               1052
#define IDC_BC_FILTERCLEAR              1053
#define IDC_BC_PROXYIP                  1055
#define IDC_BC_PROXYPORT                1056
#define IDC_BC_PROXYIP_S                1057
#define IDC_BC_PROXYPORT_S              1058
#define IDC_BC_PROXYUSER                1059
#define IDC_BC_PROXYUSER_S              1060
#define IDC_BC_PROXYPASS_S              1061
#define IDC_BC_PROXYPASS                1062
#define IDC_BC_PROXYCHECK               1063
#define IDC_BC_PORTCHECK                1064
#define IDC_BC_SAVEBROWSE               1064
#define ID_ADVANCED                     1064
#define IDC_TRACKERLIST                 1066
#define IDC_TRACKER_LOGINCHECK          1067
#define IDC_TRACKER_USER_S              1068
#define IDC_TRACKER_PASS_S              1069
#define IDC_TRACKER_USER                1070
#define IDC_TRACKER_PASS                1071
#define IDC_DEBUGFILECHECK              1078
#define IDC_DEBUGDEBUGCHECK             1079
#define IDC_GROUP_TORRENT               1080
#define IDC_GROUP_TRACKER               1081
#define IDC_UPDATESTAT                  1082
#define IDC_NC                          1083
#define IDC_ADVDLG_VERSION              1084
#define IDC_LANGLIST					1085
#define IDC_EDITABOUT					1086
#define IDC_SC_ENABLE_PE                1087
#define IDC_SC_PE_ENC_PLAIN             1088
#define IDC_SC_PE_ENC_RC4               1089
#define IDC_SC_PE_ENC_BOTH              1090
#define IDC_SC_PE_ENC_RC4_PERFER        1091
#define IDC_SC_PE_CP_IN_FORCED          1092
#define IDC_SC_PE_CP_IN_DISABLED        1093
#define IDC_SC_PE_CP_IN_ENABLED         1094
#define IDC_SC_PE_CP_OUT_DISABLED       1095
#define IDC_SC_PE_CP_OUT_ENABLED        1096
#define IDC_SC_PE_CP_OUT_FORCED         1097
#define IDC_SC_HELP_LINK                1098
#define IDC_BC_HELP_LINK                1098
#define IDC_BC_CON_WHY                  1099
#define IDC_BC_HALFCONN_CHECK           1100
#define IDC_BC_HALFCONN_NUM             1101
#define ED_CON                          3000
#define IDPANE_STATUS                   40000
#define ID_LVM_RESUME                   40000
#define ID_TLVM_NEW                     40000
#define IDPANE_CAPS_INDICATOR           40001
#define ID_TLVM_EDIT                    40001
#define ID__LVM_PAUSE                   40001
#define IDPANE_DHT                      40002
#define ID_LVM_STOP                     40002
#define ID_TLVM_DELETE                  40002
#define IDPANE_FILTER                   40003
#define ID_LVM_REANNOUNCE               40003
#define IDS_TRYANOTHERPORT              40004
#define ID_LVM_REMOVE_T                 40004
#define ID_TRAY_OPENHALITE              40004
#define IDS_DHTTRYANOTHERPORT           40005
#define ID_LVM_REMOVE_TD                40005
#define ID_TRAY_PAUSEALL                40005
#define IDS_SAVEPROMPT                  40006
#define ID_TRAY_RESUMEALL               40006
#define HAL_EVENTNONE                   40007
#define HAL_EVENTDEBUG                  40008
#define HAL_EVENTINFO                   40009
#define ID_TRAY_EXIT                    40009
#define HAL_EVENTCRITICAL               40010
#define HAL_PEERALERT                   40011
#define HAL_EVENT_XMLEXP                40012
#define IDS_NA                          40013
#define HAL_EVENT_TORRENTEXP            40014
#define HAL_EVENT_INVTORRENT            40015
#define HAL_DOWNLOAD_SUMMARY            40016
#define HAL_DHT_ON                      40017
#define HAL_DHT_OFF                     40018
#define HAL_IPFILTER_ON                 40019
#define HAL_IPFILTER_OFF                40020
#define HAL_EVENT_STDEXP                40021
#define HAL_DOWN_RATES                  40022
#define HAL_NOT_LISTENING               40023
#define HAL_PORT_OPEN                   40024
#define HAL_VERSION_STRING              40025
#define HAL_LISTVIEW_COLUMNS            40026
#define HAL_DEBUG_LISTVIEW_COLUMNS      40027
#define HAL_TRACKER_LISTVIEW_COLUMNS	40028
#define HAL_DIALOGPEER_LISTVIEW_COS     40029
#define HAL_EVENT_EXP                   40030
#define HAL_EVENT_XML_EXP               40031
#define HAL_EVENT_UNICODE_EXP           40032
#define HAL_EVENT_DEBUG                 40036
#define HAL_EVENT_UNCLASSIFIED          40033
#define HAL_EVENT_PEER                  40034
#define HAL_EVENT_TRACKER               40035
#define HAL_PEER_INTERESTING            40037
#define HAL_PEER_CHOKED                 40038
#define HAL_PEER_REMOTE_INTERESTING     40039
#define HAL_PEER_REMOTE_CHOKED          40040
#define HAL_PEER_SUPPORT_EXTENSIONS     40041
#define HAL_PEER_LOCAL_CONNECTION       40042
#define HAL_PEER_HANDSHAKE              40043
#define HAL_PEER_CONNECTING             40044
#define HAL_PEER_QUEUED                 40045
#define HAL_PEER_RC4_ENCRYPTED          40046
#define HAL_PEER_PLAINTEXT_ENCRYPTED    40047
#define HAL_TORRENT_QUEUED_CHECKING     40050
#define HAL_TORRENT_CHECKING_FILES      40051
#define HAL_TORRENT_CONNECTING          40052
#define HAL_TORRENT_DOWNLOADING         40053
#define HAL_TORRENT_FINISHED            40054
#define HAL_TORRENT_SEEDING             40055
#define HAL_TORRENT_ALLOCATING          40056
#define HAL_TORRENT_QUEUED              40057
#define HAL_TORRENT_STOPPED             40058
#define HAL_TORRENT_PAUSED              40059
#define HAL_TORRENT_METADATA            40060
#define HAL_DIALOGPEER_LISTVIEW_ADV		40070
#define HAL_ABOUT_BOX					40080
#define HAL_FOLDER_SELECT				40081
#define HAL_TORRENT_TAB				    40082
#define HAL_PEERS_TAB				    40083
#define HAL_TRACKER_TAB				    40084
#define HAL_DEBUG_TAB				    40085
#define HAL_INCORRECT_ENCODING_LEVEL	40086
#define HAL_INCORRECT_CONNECT_POLICY    40087
#define HAL_LISTVIEW_DEFAULTS			40088
#define HAL_DEBUG_LISTVIEW_DEFAULTS		40089
#define HAL_TRACKER_LISTVIEW_DEFAULTS	40090
#define HAL_DIALOGPEER_LISTVIEW_COS_DEFAULTS 40091
#define HAL_DIALOGPEER_LISTVIEW_ADV_DEFAULTS 40092
#define HAL_COMPLETED_SUMMARY           40093
#define HAL_DOWNLOADT_SUMMARY           40094
#define HAL_AUTOSORT					40095
#define ID_LVM_AUTOSORT					40096
#define IDR_BLANK_MENU					40097
#define HAL_PAYLOAD_SUMMARY				40098
#define HAL_NAME_SUMMARY				40099
#define IDC_NAME_STATUS					40100
#define IDC_SECOND						40101
#define IDC_TRANSFERED					40102
#define IDC_REMAINING					40103
#define IDC_RATE						40104
#define HAL_NAME_STATUS					40105
#define HAL_SECOND						40106
#define HAL_TRANSFERED					40107
#define HAL_REMAINING					40108
#define HAL_RATE						40109
#define IDC_RICHEDITABOUT				40110
#define IDR_ABOUT_TEXT					40111
#define HALITE_RTF_RES_TYPE				40112

#define IDC_NAME_STATUS_LABEL			40113
#define IDC_PEERS_LABEL					40114
#define IDC_TRANSFERED_LABEL			40115
#define IDC_REMAINING_LABEL				40116
#define IDC_RATE_LABEL					40117
#define IDC_SEEDS_LABEL					40118
#define IDC_OVERHEAD_LABEL				40119
#define IDC_ETA_LABEL					40120
#define IDC_RATIO_LABEL					40121
	
#define IDC_SEEDS						40122
#define IDC_OVERHEAD					40123
//#define IDC_ETA							40124
//#define IDC_RATIO						40125
	
//#define IDC_NAME_STATUS					40126
#define IDC_PEERS						40127
//#define IDC_TRANSFERED					40128
//#define IDC_REMAINING					40129
//#define IDC_RATE						40130
