#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDC_DEBUGLISTVIEW               1
#define IDR_LISTVIEW_MENU               101
#define IDD_CONFIGBIT                   102
#define IDD_CONFIGREMOTE                103
#define IDD_ABOUT                       104
#define IDD_CLOSESPLASH                 105
#define IDD_HALITEDLG                   106
#define IDR_TRAY_MENU                   107
#define IDD_NEWTORRENT                  111
#define IDD_CONFIGGENERAL               112
#define IDD_ADVHALITEDLG                114
#define IDR_APP_ICON                    114
#define IDD_THEMETEST                   115
#define IDD_DEBUGDIALOG                 116
#define IDD_PROGRESS                    117
#define IDD_CONFIGTORRENT               118
#define IDD_ADVOVERVIEW                 119
#define IDD_ADVTRACKER                  120
#define IDD_ADVDEBUGLOG                 121
#define IDR_MAINFRAME                   128
#define IDD_TRACKEDIT                   130
#define IDR_TRACKERLV_MENU              132
#define IDC_TRANS                       1000
#define LISTPEERS                       1000
#define IDC_RATIOSTAT                   1001
#define IDC_TRACKER_EDIT_TIER           1001
#define IDC_RATIOESTATIC                1002
#define IDC_TRACKER_EDIT_URL            1002
#define IDC_TRACKER_RESET               1002
#define IDC_BC_DHTPORT_S                1003
#define IDC_TRACKER_APPLY               1003
#define TORRENTPROG                     1003
#define IDC_BC_DHTPORT                  1004
#define IDC_COMPLETE                    1004
#define ID_SETTINGS                     1004
#define IDC_BC_PROMPTSAVE               1005
#define ID_RESUME                       1005
#define ID_PAUSE                        1006
#define IDC_SPLASH_MSG                  1007
#define IDC_NAME                        1008
#define IDC_TRACKER                     1009
#define IDC_STATUS                      1010
#define IDC_AVAIL                       1011
#define BTNREMOVE                       1012
#define BTNREANNOUNCE                   1013
#define IDC_EDITTLU                     1014
#define IDC_EDITTLD                     1015
#define IDC_EDITNCD                     1016
#define IDC_EDITNCU                     1017
#define IDC_EDITRATIO                   1018
#define IDC_TLD                         1019
#define IDC_TLU                         1020
#define IDC_TL                          1021
#define IDC_NCU                         1022
#define IDC_NCD                         1023
#define IDC_DETAILS_GROUP               1024
#define IDC_BC_MAXCONN                  1025
#define IDC_UPDATE                      1025
#define IDC_BC_TMAXCONN                 1026
#define IDC_REMOTECTRL                  1026
#define IDC_BC_MAXUP                    1027
#define IDC_RATIO                       1027
#define IDC_BC_TMAXUP                   1028
#define IDC_ETA                         1028
#define IDC_REMOTEPORT                  1028
#define IDC_BC_PORTFROM                 1029
#define IDC_BC_SAVEFOLDER               1029
#define IDC_BC_PORTTO                   1030
#define IDC_BC_DOWNRATE                 1031
#define IDC_BC_TDOWNRATE                1032
#define IDC_BC_UPRATE                   1033
#define BTNPAUSE                        1034
#define IDC_BC_TUPRATE                  1034
#define IDC_NEWT_BROWSE                 1035
#define IDC_NEWT_FILE                   1036
#define IDC_NEWT_TRACKER                1037
#define IDC_NEWT_LISTTRACKERS           1038
#define IDC_NEWT_DHTNODE                1039
#define IDC_NEWT_ADDTRACKER             1040
#define IDC_BUTTON1                     1041
#define IDC_EDIT1                       1042
#define IDC_EDIT2                       1043
#define IDC_GENERAL_ONEINST             1043
#define IDC_GENERAL_ADVGUI              1044
#define IDC_TAB                         1044
#define IDC_CHECK1                      1045
#define IDC_GENERAL_TRAY                1045
#define IDC_RADIO1                      1046
#define IDC_BC_DHT                      1048
#define IDC_PROG_PROGRESS               1048
#define IDC_BC_FILTERCHECK              1049
#define IDC_PROG_CANCEL                 1049
#define IDC_BC_FILTERLOAD               1052
#define IDC_BC_FILTERCLEAR              1053
#define IDC_BC_PROXYIP                  1055
#define IDC_BC_PROXYPORT                1056
#define IDC_BC_PROXYIP_S                1057
#define IDC_BC_PROXYPORT_S              1058
#define IDC_BC_PROXYUSER                1059
#define IDC_BC_PROXYUSER_S              1060
#define IDC_BC_PROXYPASS_S              1061
#define IDC_BC_PROXYPASS                1062
#define IDC_BC_PROXYCHECK               1063
#define IDC_BC_PORTCHECK                1064
#define IDC_BC_SAVEBROWSE               1064
#define ID_ADVANCED                     1064
#define IDC_TRACKERLIST                 1066
#define IDC_TRACKER_LOGINCHECK          1067
#define IDC_TRACKER_USER_S              1068
#define IDC_TRACKER_PASS_S              1069
#define IDC_TRACKER_USER                1070
#define IDC_TRACKER_PASS                1071
#define IDC_DEBUGFILECHECK              1078
#define IDC_DEBUGDEBUGCHECK             1079
#define IDC_GROUP_TORRENT               1080
#define IDC_GROUP_TRACKER               1081
#define IDC_UPDATESTAT                  1082
#define IDC_NC                          1083
#define IDC_ADVDLG_VERSION              1084
#define ED_CON                          3000
#define IDPANE_STATUS                   40000
#define ID_LVM_RESUME                   40000
#define ID_TLVM_NEW                     40000
#define IDPANE_CAPS_INDICATOR           40001
#define ID_TLVM_EDIT                    40001
#define ID__LVM_PAUSE                   40001
#define IDPANE_DHT                      40002
#define ID_LVM_STOP                     40002
#define ID_TLVM_DELETE                  40002
#define IDPANE_FILTER                   40003
#define ID_LVM_REANNOUNCE               40003
#define IDS_TRYANOTHERPORT              40004
#define ID_LVM_REMOVE_T                 40004
#define ID_TRAY_OPENHALITE              40004
#define IDS_DHTTRYANOTHERPORT           40005
#define ID_LVM_REMOVE_TD                40005
#define ID_TRAY_PAUSEALL                40005
#define IDS_SAVEPROMPT                  40006
#define ID_TRAY_RESUMEALL               40006
#define HAL_EVENTNONE                   40007
#define HAL_EVENTDEBUG                  40008
#define HAL_EVENTINFO                   40009
#define ID_TRAY_EXIT                    40009
#define HAL_EVENTCRITICAL               40010
#define HAL_PEERALERT                   40011
#define HAL_EVENT_XMLEXP                40012
#define IDS_NA                          40013
#define HAL_EVENT_TORRENTEXP            40014
#define HAL_EVENT_INVTORRENT            40015
#define HAL_DOWNLOAD_SUMMARY            40016
#define HAL_DHT_ON                      40017
#define HAL_DHT_OFF                     40018
#define HAL_IPFILTER_ON                 40019
#define HAL_IPFILTER_OFF                40020
#define HAL_EVENT_STDEXP                40021
#define HAL_DOWN_RATES                  40022
#define HAL_NOT_LISTENING               40023
#define HAL_PORT_OPEN                   40024
#define HAL_VERSION_STRING              40025
