
//         Copyright Eóin O'Callaghan 2006 - 2007.
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE_1_0.txt or copy at
//          http://www.boost.org/LICENSE_1_0.txt)

#ifndef HAL_STATIC
#define HAL_STATIC (-1)
#endif

#define HALITE_LANGUAGE					10
#define HAL_DEBUGLISTVIEW               1
#define HAL_LISTVIEW_MENU               101
#define HAL_CONFIGBIT                   102
#define HAL_CONFIGREMOTE                103
#define HAL_CONFIGSECURITY              108
#define HAL_CONFIGPROXY                 109
#define HAL_CONFIGGLOBAL				110
#define HAL_ABOUT                       104
#define HAL_CLOSESPLASH                 105
#define HAL_HALITEDLG                   106
#define HAL_TRAY_MENU                   107
#define HAL_CONFIGPORTS					111
#define HAL_CONFIGGENERAL               112
#define HAL_ADVHALITEDLG                114
#define HAL_APP_ICON                    114
#define HAL_THEMETEST                   115
#define HAL_DEBUGDIALOG                 116
#define HAL_CONFIGTORRENT               118
#define HAL_ADVOVERVIEW                 119
#define HAL_ADVTRACKER                  120
#define HAL_ADVDEBUGLOG                 121
#define HAL_MAINFRAME                   128
#define HAL_TRACKEDIT                   130
#define HAL_ADVPEER                     131
#define HAL_NEWTORRENT					133
#define HAL_NEWT_TRACKERS				134
#define HAL_NEWT_PEERS					135
#define HAL_TRACKERLV_MENU              132
#define	HAL_GENERIC_ADD_LV_MENU			136
#define	HAL_PEEREDIT					137
#define HAL_NEWT_FILES					138
#define HAL_TRANS_SES                   1004
#define HAL_TRANS_ETA                   1005
#define HAL_PEERPROXY                   1000
#define HAL_WEBPROXY                    1001
#define HAL_TRACKERPROXY                1002
#define HAL_DHTPROXY                    1003
#define HAL_TRANS                       1000
#define LISTPEERS                       1000
#define HAL_PEERLIST                    1000
#define HAL_RATIOSTAT                   1001
#define HAL_PEER_EDIT_TYPE		        1001
#define HAL_RATIOESTATIC                1002
#define HAL_PEER_EDIT_URL	            1002
#define HAL_TRACKER_RESET               1002
#define HAL_BC_DHTPORT_S                1003
#define HAL_TRACKER_APPLY               1003
#define TORRENTPROG                     1003
#define HAL_BC_DHTPORT                  1004
#define HAL_COMPLETE                    1004
#define ID_SETTINGS                     1004
#define HAL_BC_PROMPTSAVE               1005
#define ID_RESUME                       1005
#define ID_PAUSE                        1006
#define HAL_SPLASH_MSG                  1007
#define HAL_NAME                        1008
#define HAL_TRACKER                     1009
#define HAL_STATUS                      1010
#define HAL_AVAIL                       1011
#define HAL_EDITTLU                     1014
#define HAL_EDITTLD                     1015
#define HAL_EDITNCD                     1016
#define HAL_EDITNCU                     1017
#define HAL_EDITRATIO                   1018
#define HAL_TLD                         1019
#define BTNREMOVE                       1012
#define BTNREANNOUNCE                   1013
#define BTNPAUSE                        1034
#define HAL_TLU                         1020
#define HAL_TL                          1021
#define HAL_NCU                         1022
#define HAL_NCD                         1023
#define HAL_DETAILS_GROUP               1024
#define HAL_BC_MAXCONN                  1025
#define HAL_UPDATE                      1025
#define HAL_BC_TMAXCONN                 1026
#define HAL_REMOTECTRL                  1026
#define HAL_BC_MAXUP                    1027
#define HAL_RATIO                       1027
#define HAL_BC_TMAXUP                   1028
#define HAL_ETA                         1028
#define HAL_REMOTEPORT                  1028
#define HAL_BC_PORTFROM                 1029
#define HAL_BC_SAVEFOLDER               1029
#define HAL_BC_PORTTO                   1030
#define HAL_BC_DOWNRATE                 1031
#define HAL_BC_TDOWNRATE                1032
#define HAL_BC_UPRATE                   1033
#define BTNPAUSE                        1034
#define HAL_BC_TUPRATE                  1034
#define HAL_NEWT_BROWSE                 1035
#define HAL_NEWT_FILE                   1036
#define HAL_NEWT_TRACKER                1037
#define HAL_NEWT_LISTTRACKERS           1038
#define HAL_NEWT_DHTNODE                1039
#define HAL_NEWT_ADDTRACKER             1040
#define HAL_BUTTON1                     1041
#define HAL_EDIT1                       1042
#define HAL_EDIT2                       1043
#define HAL_GENERAL_ONEINST             1043
#define HAL_GENERAL_ADVGUI              1044
#define HAL_TAB                         1044
#define HAL_CHECK1                      1045
#define HAL_GENERAL_TRAY                1045
#define HAL_RADIO1                      1046
#define HAL_BC_DHT                      1048
#define HAL_BC_FILTERCHECK              1049
#define HAL_BC_FILTERLOAD               1052
#define HAL_BC_FILTERCLEAR              1053
#define HAL_BC_PROXYIP                  1055
#define HAL_BC_PROXYPORT                1056
#define HAL_BC_PROXYIP_S                1057
#define HAL_BC_PROXYPORT_S              1058
#define HAL_BC_PROXYUSER                1059
#define HAL_BC_PROXYUSER_S              1060
#define HAL_BC_PROXYPASS_S              1061
#define HAL_BC_PROXYPASS                1062
#define HAL_BC_PROXYCHECK               1063
#define HAL_BC_PORTCHECK                1064
#define HAL_BC_SAVEBROWSE               1064
#define ID_ADVANCED                     1064
#define HAL_TRACKERLIST                 1066
#define HAL_TRACKER_LOGINCHECK          1067
#define HAL_TRACKER_USER_S              1068
#define HAL_TRACKER_PASS_S              1069
#define HAL_TRACKER_USER                1070
#define HAL_TRACKER_PASS                1071
#define HAL_DEBUGFILECHECK              1078
#define HAL_DEBUGDEBUGCHECK             1079
#define HAL_GROUP_TORRENT               1080
#define HAL_GROUP_TRACKER               1081
#define HAL_UPDATESTAT                  1082
#define HAL_NC                          1083
#define HAL_ADVDLG_VERSION              1084
#define HAL_LANGLIST					1085
#define HAL_EDITABOUT					1086
#define HAL_SC_ENABLE_PE                1087
#define HAL_SC_PE_ENC_PLAIN             1088
#define HAL_SC_PE_ENC_RC4               1089
#define HAL_SC_PE_ENC_BOTH              1090
#define HAL_SC_PE_ENC_RC4_PERFER        1091
#define HAL_SC_PE_CP_IN_FORCED          1092
#define HAL_SC_PE_CP_IN_DISABLED        1093
#define HAL_SC_PE_CP_IN_ENABLED         1094
#define HAL_SC_PE_CP_OUT_DISABLED       1095
#define HAL_SC_PE_CP_OUT_ENABLED        1096
#define HAL_SC_PE_CP_OUT_FORCED         1097
#define HAL_SC_HELP_LINK                1098
#define HAL_BC_HELP_LINK                1098
#define HAL_BC_CON_WHY                  1099
#define HAL_BC_HALFCONN_CHECK           1100
#define HAL_BC_HALFCONN_NUM             1101
#define ED_CON                          3000
#define IDPANE_STATUS                   40000
#define ID_LVM_RESUME                   40000
#define IDPANE_CAPS_INDICATOR           40001
#define ID__LVM_PAUSE                   40001
#define IDPANE_DHT                      40002
#define ID_LVM_STOP                     40002
#define IDPANE_FILTER                   40003
#define ID_LVM_REANNOUNCE               40003
#define IDS_TRYANOTHERPORT              40004
#define ID_LVM_REMOVE_T                 40004
#define ID_TRAY_OPENHALITE              40004
#define IDS_DHTTRYANOTHERPORT           40005
#define ID_LVM_REMOVE_TD                40005
#define ID_TRAY_PAUSEALL                40005
#define IDS_SAVEPROMPT                  40006
#define ID_TRAY_RESUMEALL               40006
#define HAL_EVENTNONE                   40007
#define HAL_EVENTDEBUG                  40008
#define HAL_EVENTINFO                   40009
#define HAL_EVENTWARNING				39999
#define ID_TRAY_EXIT                    40009
#define HAL_EVENTCRITICAL               40010
#define HAL_EVENT_XMLEXP                40012
#define IDS_NA                          40013
#define HAL_DOWNLOAD_SUMMARY            40016
#define HAL_DHT_ON                      40017
#define HAL_DHT_OFF                     40018
#define HAL_IPFILTER_ON                 40019
#define HAL_IPFILTER_OFF                40020
#define HAL_EVENT_STDEXP                40021
#define HAL_DOWN_RATES                  40022
#define HAL_NOT_LISTENING               40023
#define HAL_PORT_OPEN                   40024
#define HAL_VERSION_STRING              40025
#define HAL_LISTVIEW_COLUMNS            40026
#define HAL_DEBUG_LISTVIEW_COLUMNS      40027
#define HAL_TRACKER_LISTVIEW_COLUMNS	40028
#define HAL_DIALOGPEER_LISTVIEW_COS     40029
#define HAL_DIALOGPEER_LISTVIEW_ADV		40070
#define HAL_ABOUT_BOX					40080
#define HAL_FOLDER_SELECT				40081
#define HAL_TORRENT_TAB				    40082
#define HAL_PEERS_TAB				    40083
#define HAL_TRACKER_TAB				    40084
#define HAL_DEBUG_TAB				    40085
#define HAL_LISTVIEW_DEFAULTS			40088
#define HAL_DEBUG_LISTVIEW_DEFAULTS		40089
#define HAL_TRACKER_LISTVIEW_DEFAULTS	40090
#define HAL_DIALOGPEER_LISTVIEW_COS_DEFAULTS 40091
#define HAL_DIALOGPEER_LISTVIEW_ADV_DEFAULTS 40092
#define HAL_COMPLETED_SUMMARY           40093
#define HAL_DOWNLOADT_SUMMARY           40094
#define HAL_AUTOSORT					40095
#define ID_LVM_AUTOSORT					40096
#define HAL_BLANK_MENU					40097
#define HAL_PAYLOAD_SUMMARY				40098
#define HAL_NAME_SUMMARY				40099
#define HAL_NAME_STATUS					40100
#define HAL_SECOND						40101
#define HAL_TRANSFERED					40102
#define HAL_REMAINING					40103
#define HAL_RATE						40104
#define HAL_RICHEDITABOUT				40110
#define HAL_ABOUT_TEXT					40111
#define HALITE_RTF_RES_TYPE				40112

#define HAL_NAME_STATUS_LABEL			40113
#define HAL_PEERS_LABEL					40114
#define HAL_TRANSFERED_LABEL			40115
#define HAL_REMAINING_LABEL				40116
#define HAL_RATE_LABEL					40117
#define HAL_SEEDS_LABEL					40118
#define HAL_OVERHEAD_LABEL				40119
#define HAL_ETA_LABEL					40120
#define HAL_RATIO_LABEL					40121
	
#define HAL_SEEDS						40122
#define HAL_OVERHEAD					40123
#define HAL_PEERS						40127
#define HAL_ADVFILES					40129
#define HAL_CONTAINER					40130
#define HAL_FILES_TAB				    40131
#define HAL_DIALOGFILE_LISTVIEW_ADV		40132
#define HAL_TORRENT_ROOT				40133

#define HAL_FILE_PRIORITY_0				40134
#define HAL_FILE_PRIORITY_1				40135
#define HAL_FILE_PRIORITY_2				40136
#define HAL_FILE_PRIORITY_3				40137
#define HAL_FILE_PRIORITY_4				40138
#define HAL_FILE_PRIORITY_5				40139
#define HAL_FILE_PRIORITY_6				40140
#define HAL_FILE_PRIORITY_7				40141

#define ID_HAL_FILE_PRIORITY_0			40142
#define ID_HAL_FILE_PRIORITY_1			40143
#define ID_HAL_FILE_PRIORITY_2			40144
#define ID_HAL_FILE_PRIORITY_3			40145
#define ID_HAL_FILE_PRIORITY_4			40146
#define ID_HAL_FILE_PRIORITY_5			40147
#define ID_HAL_FILE_PRIORITY_6			40148
#define ID_HAL_FILE_PRIORITY_7			40149
#define HAL_FILESLISTVIEW_MENU			40150

#define HAL_ADD_TORRENT					40200
#define HAL_CHECK_COMPACT				40201
#define HAL_CHECK_PAUSED				40202
#define HAL_INF							40203
#define HAL_HALITE						40204
#define HAL_NEWT_TRACKERLV_MENU			40300

#ifndef HAL_NA
#define HAL_NA IDS_NA
#endif

